### ISSUE TITLE
Should list an example of the user login url under "Client Considerations"

### ISSUE THREAD

**Issue by petery789** [mulesoft/docs-access-management#207]
As a new user, I don't necessarily know what would be a  working url to use based solely on "https://anypoint.mulesoft.com/accounts/login/{your_org_domain}". Should provide a working example. 

Also, who is going to define or provide "your_org_domain"? Is it going to be a property set during the SSO IdP configuration?

**Comment by sarathecoubian** [comment]
The domain name of your org is available in your user profile under settings -> organization domain. 
The org domain is selected when your organization is created.
